print("Ciudad","pais","comunidad",sep="\t")
print("nombre","edad","ciudad",sep="\t")
print("Ana","25","corea del sur",sep="\t")
print("Mario","30","paris",sep="\t")
print("Luisa","18","Honduras",sep="\t")
holisss(como estas?)
print("Mnago","Manzana","Durazno",sep="\t")
